version: "2"

linters:
  default: standard
  enable:
    - misspell
    - gocritic
    - copyloopvar
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain

formatters:
  enable:
    - gofmt
    - goimports
